/*
alertmanager

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package labs_alert_manager_client

import (
	"encoding/json"
)

// checks if the PaginationSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationSchema{}

// PaginationSchema struct for PaginationSchema
type PaginationSchema struct {
	Page int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
	Rows []map[string]interface{} `json:"rows"`
	TotalRows int32 `json:"totalRows"`
}

// NewPaginationSchema instantiates a new PaginationSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationSchema(page int32, pageSize int32, rows []map[string]interface{}, totalRows int32) *PaginationSchema {
	this := PaginationSchema{}
	this.Page = page
	this.PageSize = pageSize
	this.Rows = rows
	this.TotalRows = totalRows
	return &this
}

// NewPaginationSchemaWithDefaults instantiates a new PaginationSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationSchemaWithDefaults() *PaginationSchema {
	this := PaginationSchema{}
	return &this
}

// GetPage returns the Page field value
func (o *PaginationSchema) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PaginationSchema) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PaginationSchema) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *PaginationSchema) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *PaginationSchema) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *PaginationSchema) SetPageSize(v int32) {
	o.PageSize = v
}

// GetRows returns the Rows field value
func (o *PaginationSchema) GetRows() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value
// and a boolean to check if the value has been set.
func (o *PaginationSchema) GetRowsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rows, true
}

// SetRows sets field value
func (o *PaginationSchema) SetRows(v []map[string]interface{}) {
	o.Rows = v
}

// GetTotalRows returns the TotalRows field value
func (o *PaginationSchema) GetTotalRows() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalRows
}

// GetTotalRowsOk returns a tuple with the TotalRows field value
// and a boolean to check if the value has been set.
func (o *PaginationSchema) GetTotalRowsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRows, true
}

// SetTotalRows sets field value
func (o *PaginationSchema) SetTotalRows(v int32) {
	o.TotalRows = v
}

func (o PaginationSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["pageSize"] = o.PageSize
	toSerialize["rows"] = o.Rows
	toSerialize["totalRows"] = o.TotalRows
	return toSerialize, nil
}

type NullablePaginationSchema struct {
	value *PaginationSchema
	isSet bool
}

func (v NullablePaginationSchema) Get() *PaginationSchema {
	return v.value
}

func (v *NullablePaginationSchema) Set(val *PaginationSchema) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationSchema) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationSchema(val *PaginationSchema) *NullablePaginationSchema {
	return &NullablePaginationSchema{value: val, isSet: true}
}

func (v NullablePaginationSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


